### ISSUE TITLE
TMP directory in v0.6.3

### ISSUE THREAD

**Issue by ManfredSchmucker** [SamSchott/maestral-dropbox#100]
It looks like that the current version (v0.6.3) ignores the user environment variable $TMP and instead uses /tmp as the temporary directory for downloads. In my case that is an issue as my /tmp is only 64Mb big.

**Comment by ManfredSchmucker** [comment]
I'm sorry. My $TMP directory didn't had the required permissions. All good now.

**Comment by SamSchott** [comment]
No worries, glad you fixed it. Just to check, did Maestral show any error messages? This is one of those edge cases which I haven't really tested, but ideally the GUI should show a useful pop-up.
