### ISSUE TITLE
Allow for choosing whole Dropbox sync in the cli

### ISSUE THREAD

**Issue by coxackie** [SamSchott/maestral-dropbox#102]
Last time I `maestral link`(it was about a month ago) through cli I had to manually choose which folders had to be excluded. I do not recall an option to simply sync the whole dropbox. This could be helpful in cases there are too many folders to have to choose from, in which case, one could simply exclude later. I think a question of the form `Sync the whole dropbox; otherwise, choose first-level folder to sync later (Y/n)` or something better-worded could be a solution.

**Comment by SamSchott** [comment]
Good point!
