### ISSUE TITLE
[BUG] Timestamps are logged twice when logging to journald

### ISSUE THREAD

**Issue by peterhoeg** [SamSchott/maestral-dropbox#105]
**Describe the bug**

As also mentioned in #53 where it was mixed up with a few other issues, when logging to journald we get the timestamp twice - once from maestral and once from journald:

```
Mar 31 23:12:50 dolores /nix/store/rdx71dy6c2ac5nbbhip47sw2nd953zz2-maestral-0.6.3/bin/maestral[3767575]: Downloading 538/1643...
Mar 31 23:12:50 dolores maestral[3767575]: 2020-03-31 23:12:50 maestral.sync INFO: Downloading 538/1643...
```

**To Reproduce**
Run maestral under systemd

**Expected behaviour**
When running under systemd and logging to journald, maestral should not be outputting the timestamp.

**System (please complete the following information):**
 - Maestral version: 0.6.3
 - OS: NixOS
 - Desktop environment: KDE 5.17
 - Qt version: 5.12.7

**Comment by SamSchott** [comment]
Thanks for the report, I thought this was fixed. Is it possible that the journal just captures the output from stdout? Because the explicit journal logging handler is definitely set to only include the log message without time stamps.

**Comment by peterhoeg** [comment]
> Is it possible that the journal just captures the output from stdout?

It does, yes. So you are basically saying that the first line in the output above is what is logged directly to journald and the 2nd is then from stdout? I see 2 options:

1. If we are detecting systemd, send everything to journald (or have a flag that forces it)
2. If you don't need to log anything special to journald (ie, using none of the special fields), then drop that and just use stdout/stderr but without the additional time info.

**Comment by SamSchott** [comment]
Yes, the output seems to be duplicated. I do use special fields in case of exceptions, while stdout just gets the whole traceback dumped to it.

I have opted for the first option now, disable logging to stdout if run from systemd. Stdout is already disabled by default except when the `--foreground` flag is used. Now, it will only be enabled if the `--foreground` is used and Maestral does not detect systemd.

You'll have to wait a little for this to show up in either a dev or release version on PyPI...

**Comment by peterhoeg** [comment]
> You'll have to wait a little for this to show up in either a dev or release version on PyPI...

I'll live... ;-)

Thanks for the quick turnaround.

One thing to keep in mind though - would it make sense to have different flags depending on the supervisor under which it is run? Instead of trying to be clever about when to do what, we could have  `--systemd` and `--launchd` flags that just do the right thing instead of having `--foreground` do different things depending on the environment. Explicit behaviour is much nicer than implicit from a maintenance point of view.

**Comment by SamSchott** [comment]
I understand the preference of explicit flags. However, they really would not do much at the moment apart from clutter the CLI: there is no specific behaviour in case of launchd and it makes sense to always enable journal logging in case of systemd. 

I am more inclined to have an explicit flag for logging to stdout. The API already has this keyword argument, it is just not exposed to the user via the CLI.
