### ISSUE TITLE
[BUG] Maestral doesn't compleatly quit using the GUI quit option

### ISSUE THREAD

**Issue by 1nikolas** [SamSchott/maestral-dropbox#110]
**Describe the bug**
When I start the sync, it loops "uploading 1/{total files}" and "indexing local changes" on the notification right click. No file is actually uploaded and sync issues says no issues. Only folder is created.

**To Reproduce**
Start the sync on raspberry pi

**Expected behaviour**
Upload the files

**System (please complete the following information):**
 - Maestral version: latest
 - OS: Raspbian
 - Desktop environment: doesnt matter
 - Qt version: doesnt matter

**Additional context**
It loops between these two
![Screenshot_Solid_Explorer_20200404-175253](https://user-images.githubusercontent.com/30593419/78453892-47840980-769d-11ea-9b2b-e7ec0f0c892d.png)
![Screenshot_VNC_Viewer_20200404-174837](https://user-images.githubusercontent.com/30593419/78453894-4f43ae00-769d-11ea-8bdc-014c106f5518.png)

**Comment by SamSchott** [comment]
Strange, I have never seen this before. It almost looks like the internet connection is interrupted during the upload - local changes are only indexed when syncing is restarted. 

Could post the log output? To do so, you can first clear the current logs and then set the log level to DEBUG. When you start maestral again, a fresh set of log messages will saved. The commands are:

```shell
maestral log clear
maestral log level DEBUG
maestral start
maestral log show
```

**Comment by 1nikolas** [comment]
For some reason `maestral start` says failed

**Comment by 1nikolas** [comment]
gui launches just fine. also the logs are basically "file created" events of my files (multiple times)

**Comment by 1nikolas** [comment]
it can upload small files though.. Maybe my internet has issues. I'll check it

**Comment by 1nikolas** [comment]
![Speedtest by Ookla - The Global Broadband Speed Test 2020-04-04 10 PM-38-11](https://user-images.githubusercontent.com/30593419/78459931-69918200-76c5-11ea-8969-64ed76f7a969.png)
okay clearly my internet has problems. I'm closing this issue

**Comment by SamSchott** [comment]
Good to know. You had me concerned.

**Comment by 1nikolas** [comment]
> Good to know. You had me concerned.

its because of the quarantine, everyone is at home now and there is higher internet usage

**Comment by SamSchott** [comment]
You did actually stumble upon a minor bug. Instead of retrying the initial upload until the connection works again, maestral should instead pause syncing until a good connection can be established. It was a communication issue between threads. But it does not really do any harm, just confuses the users...

**Comment by 1nikolas** [comment]
> You did actually stumble upon a minor bug. Instead of retrying the initial upload until the connection works again, maestral should instead pause syncing until a good connection can be established. It was a communication issue between threads. But it does not really do any harm, just confuses the users...

But I let it a few hours and it didn't upload a single file. I just tried uploading a file with curl to transfer.sh and it worked just fine (it took 10-20 mins for a 10mb file). So either the "connection check" is taking too much to finish, or the file starts uploading from 0 after connection is restored.. 
Either way that's not very important, it should work fine after my connection is restored, not a big deal

**Comment by SamSchott** [comment]
Yes, the upload starts from scratch once a connection is reestablished. This could be handled better but would require keeping track of interrupted uploads. Plus, there currently is a hardcoded timeout for http requests which most definitely will be reached at 1 MB / min or slower. Maestral currently does not adopt well to slow internet connections. It's not pandemic safe.

**Comment by SamSchott** [comment]
I have just read through your install instructions for Raspberry Pi. Two notes:

1) I think instructions on how to install Python 3.6 are outside the scope of this wiki. If you don't mind, I will replace the section with a link to instructions elsewhere. 

2) Is it really necessary to build PyQt5 form source? Does `apt install python3-pyqt5` not work? Also, you say that "If you have a Raspberry Pi 4 feel free to skip this". What changed with Pi 4?

**Comment by 1nikolas** [comment]
Update: I looked more into it. I was trying to find why my internet is so slow and I found out that the Raspberry pi was using all my network's traffic. After a bit of research I somehow managed to open Maestral sync service 4-5 times (even though gui was exited all those times) and it was somehow using all my internet. After killing all the python processes my network came back to normal. So how do I know it was Maestral that using up the internet? i ran `iptraf` and I saw traffic being uploaded to Dropbox IPs, so that was definitely it. 
Now that I oppened Maestral once, it seems to work just fine on uploading files so after all this actually is a bug so I'm reopening the issue

**Comment by 1nikolas** [comment]
> I have just read through your install instructions for Raspberry Pi. Two notes:
> 
>     1. I think instructions on how to install Python 3.6 are outside the scope of this wiki. If you don't mind, I will replace the section with a link to instructions elsewhere.
> 
>     2. Is it really necessary to build PyQt5 form source? Does `apt install python3-pyqt5` not work? Also, you say that "If you have a Raspberry Pi 4 feel free to skip this". What changed with Pi 4?

1 Okay that's fine
2 I don't know, I have to try it first
Raspberry pi 4 starts at 1gb (and there are 2 and 3gb options) whereas 3 has only 500mb that's why it fails

**Comment by 1nikolas** [comment]
```
python3 -m pip install pyqt5
Collecting pyqt5
  Downloading https://files.pythonhosted.org/packages/4d/81/b9a66a28fb9a7bbeb60e266f06ebc4703e7e42b99e3609bf1b58ddd232b9/PyQt5-5.14.2.tar.gz
```
Tried it on python3 which has no pyqt5 installed and it's still trying to build it
There is a [PyWheels issue](https://github.com/piwheels/packages/issues/3) where they try to build it for the Raspberry pi. Also [their site](https://www.piwheels.org/project/PyQt5/) says that the automatic build all fail

**Comment by SamSchott** [comment]
Fair enough, it this case it makes sense to leave the build instructions.

Regarding the issue of leftover processes, Maestral should do both:

1) When exiting the GUI, it tries to gracefully shut down the daemon process. If this doesn't work, it will kill it.

2) When starting the GUI, it will attach to any existing daemon process instead of starting a new one. You can even start multiple GUI instances looking at the same daemon.

There should never be more than one daemon syncing the same folder, this could otherwise lead a whole lot of problems.

Could you verify that a PID is created for the daemon in the expected location? It should be at `~/.cache/maestral/maestral.pid` on Linux.

**Comment by 1nikolas** [comment]
There is no such file.. Maestral is working just fine
![Screenshot_VNC_Viewer_20200405-192633](https://user-images.githubusercontent.com/30593419/78504119-aae06b00-7773-11ea-8202-9cfa3c5545ba.png)

**Comment by SamSchott** [comment]
That may be the issue. To verify, could you check the following in Python?

```python
import os
from maestral.daemon import pidpath_for_config, PIDLockFile

pidfile_path = pidpath_for_config('maestral')
print(pidfile_path)
print(os.path.exists(pidfile_path))
```
And check if the file exists there? It is possible that Raspbian has a different runtime dir. Even though I would be surprised, because the logs are where they should be.

If there really is no lock file created, could you try to create one manually?

```python
pidfile = PIDLockFile(pidfile_path)
pidfile.acquire()
```

**Comment by 1nikolas** [comment]
```
pi@raspberrypi:~ $ python3.6 maestral_test.py
/run/user/1000/maestral/maestral.pid
True
```
Wikipedia [says](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard#FHS_compliance) /run is a temporary file system. Never heard of it

**Comment by SamSchott** [comment]
Good! That is absolutely fine, `/run/user/1000` is good place for PID files. They are temporary runtime files by nature.

I am still confused about the multiple daemon processes. From what I can see, PID lock files are created correctly and should be respected during startup.

**Comment by 1nikolas** [comment]
Yeah I dont know either what happened. For the time being it works fine. Anyway I'm closing the issue for now. If it happenes again I'll try to find how to reproduce it and report it properly. Thank you very much for your time, I really appreciate it!
