### ISSUE TITLE
[BUG] 0.6.4 release on osx is not accepting any command line switches anymore

### ISSUE THREAD

**Issue by T0mu** [SamSchott/maestral-dropbox#113]
Hi Sam,
I'm bothering you again....
new release introduced a bug.

**Describe the bug**
launching /Applications/Maestral.app/Contents/MacOS/main --config-name="XXX" or --verbose
or --help is not giving any result. Side effect: default config (Maestral) is always launched.
**To Reproduce**
see above

**Expected behaviour**
see above

**System (please complete the following information):**
 - Maestral version:
 - OS: MacOS Catalina

**Comment by SamSchott** [comment]
Sorry, that was an oversight when I refactored the packaging scripts. I've uploaded a fixed app bundle now.

**Comment by T0mu** [comment]
Thank you, you are most kind!

________________________________
Da: SamSchott <notifications@github.com>
Inviato: mercoledì 8 aprile 2020 22:25
A: SamSchott/maestral-dropbox <maestral-dropbox@noreply.github.com>
Cc: T0mu <t.munari@outlook.com>; Author <author@noreply.github.com>
Oggetto: Re: [SamSchott/maestral-dropbox] [BUG] 0.6.4 release on osx is not accepting any command line switches anymore (#113)


Sorry, that was an oversight when I refactored the packaging scripts. I've uploaded a fixed app bundle now.

**Comment by SamSchott** [comment]
No worries, glad it works and thanks for notifying me.
