### ISSUE TITLE
[How to?] Rename a config 

### ISSUE THREAD

**Issue by coxackie** [SamSchott/maestral-dropbox#115]
By default, `maestral` names the first configuration as `maestral`. Suppose I have set this up and after some time I want to add another config (let's call it "work"), and rename the previous "maestral" to "personal". Is this something possible right now? If not, could it be implemented?

**Comment by SamSchott** [comment]
Currently this is not possible. You can however rename the dropbox folder itself with `maestral move-dir`.

There will always be a default config since most users only have a single account, but renaming configs could be implemented.

**Comment by coxackie** [comment]
sure - but can one choose the naming of the default config? right now it seems that only `maestral` is possible. I tried at some point to set up first configuration with --config_name option different than maestral, and as far as I can remember the whole thing collapsed, most probably because it was expecting that there is by default some `maestral` config. The dropbox folder was downloading in the background, but as far as `maestral status` would go it would show inactive. Or something of that sort. I Do not recall the details now, because I erased everything and started from scratch.

**Comment by SamSchott** [comment]
You will have to pass the config name as `maestral status -c CONFIG_NAME` for it to show the status of a non-default config. The same applies to all other commands that are specific to a configuration such as `autostart`, `activity`, `ls`, etc. Apart from this inconvenience, it should just work...

**Comment by coxackie** [comment]
ok, got it, will try again at some point. feel free to close this issue, unless you want to keep it open for adding the config renaming functionality in the future.

**Comment by SamSchott** [comment]
Closing, I don't see much benefit of adding this at the moment.
