### ISSUE TITLE
[question]  "unwatched" files

### ISSUE THREAD

**Issue by eleaner** [SamSchott/maestral-dropbox#117]
Hi,

my dropbox is on a network drive,
when I add a file to dropbox there, the file-status remains "unwatched", and the whole folder remains "up to date"

how can I force synchronisation? preferably continously?

**Comment by SamSchott** [comment]
What kind of file system and platform are you using? I suspect Maestral does not get notified of file system events. As a fallback, one could just rescan the entire folder periodically (as it does when you pause and resume syncing). Relying on this for syncing however is slow and CPU intensive.

**Comment by eleaner** [comment]
its moosefs and maestral see it mounted in the docker container.
I guess it was not the best idea
Will figure something else

**Comment by SamSchott** [comment]
Sorry about that!
