### ISSUE TITLE
Improve the dropbox location

### ISSUE THREAD

**Issue by idnovic** [SamSchott/maestral-dropbox#18]
![Bildschirmfoto vom 2019-07-07 17-43-47](https://user-images.githubusercontent.com/28260793/60770879-460ebc00-a0e0-11e9-9e65-0164b0db8200.png)

I do not htink it is perfectly clear that the dropbox folder is going to be a subdirectory of the chosen directory

**Comment by SamSchott** [comment]
Good point. Will do.
