### ISSUE TITLE
shrink and set max wide

### ISSUE THREAD

**Issue by idnovic** [SamSchott/maestral-dropbox#19]
![AB137EC3-A85F-4516-B5E0-B1337F3F9A44](https://user-images.githubusercontent.com/28260793/60773595-09ef5180-a108-11e9-8c0f-89b85798e068.jpeg)
![AF6A4747-BF4B-4FA9-A28F-C9F1CD8EEDC5](https://user-images.githubusercontent.com/28260793/60773596-0a87e800-a108-11e9-9524-8e8cb50e3d43.jpeg)

It seems you need to set a max wide at this sub menu.
Maybe maximal 15 chars?

**Comment by SamSchott** [comment]
Uh, those are some long file names! Yes, it seems so.

**Comment by idnovic** [comment]
I do not have files with these names.
Was it expected that the actual file names display instead?

**Comment by idnovic** [comment]
Well okay, maybe cryptomator is responsible for those...

**Comment by SamSchott** [comment]
If you click on it, it should take you to the file! Then you can see where they are from. But yes, a maximum width would make sense.

**Comment by idnovic** [comment]
Okay the take me to the file feature works well!
Yes it is cryptomator. Those encrypted files always look strange
