### ISSUE TITLE
keyring integration done well

### ISSUE THREAD

**Issue by idnovic** [SamSchott/maestral-dropbox#23]
![Bildschirmfoto vom 2019-07-13 23-41-08](https://user-images.githubusercontent.com/28260793/61176814-0b60c400-a5b7-11e9-9ff3-953e49c5f88f.png)

Really nice.

**Comment by SamSchott** [comment]
I'm glad you like it. For people who do not encrypt their hard drive, this is certainly much safer.

**Comment by idnovic** [comment]
Even with an encrypted hard drive this is nice to have. I do not like clear text files for logins.
And some programs like to access files they are not supposed to.
