### ISSUE TITLE
Autostart options tries to launch nonexistant mercury-gui exec on Linux

### ISSUE THREAD

**Issue by logix2** [SamSchott/maestral-dropbox#25]
I'm using Maestral 0.2.0, and the option to start Maestral automatically adds an autostart entry to a nonexistant ``mercury-gui`` exec on Linux, instead of ``maestral gui``.

On Ubuntu 19.04, Maestral installed from PyPI.

**Comment by SamSchott** [comment]
@logix2, this is indeed an oversight. The correct startup script should be `maestral-gui`. `mercurygui` is another app which I am developing (a python user interface for cryostat temperature controllers...). I will fix this shorty and push an update to PyPI.

The reason why I provide an additional shell script `maestral-gui` is for the user to set environment variables before launching Maestral by manually editing `maestral-gui`. This may be used to switch to the correct python environment, or, on HiDPI screens, to set scaling factors for the Qt user interface.

**Comment by SamSchott** [comment]
This should be fixed with the latest release. Could you check?

**Comment by SamSchott** [comment]
PS: You will have to un-check and re-check "Start Maestral on login" for the login-item to be replaced.

**Comment by logix2** [comment]
Fixed, thanks!
