### ISSUE TITLE
[Feature request]: support multiple dropbox accounts

### ISSUE THREAD

**Issue by van-tienhoang** [SamSchott/maestral-dropbox#28]
Hello,

Like the title, it would be great if the application allows to use both work and personal account at the same time. It would be better if can use with multiple personal accounts.

Bests

**Comment by SamSchott** [comment]
Hi @van-tienhoang, this should fundamentally be possible - its just a question of managing the settings for different accounts.

The work would mainly be in developing the UI to handle multiple accounts in a simple, non-cluttered way. I don't have the time to do this at the moment, but do of course welcome suggestions in design and pull requests.

**Comment by SamSchott** [comment]
The latest beta introduces experimental support for multiple Dropbox accounts. This works by creating separate configurations through the command line with `maestral env new "name"` and then selecting which configuration to use when running an instance of Maestral:
```shell
maestral gui --config-name="name"
```
Install and usage instructions are available under [releases](https://github.com/SamSchott/maestral-dropbox/releases/tag/v0.2.7-beta1). Feel free to try it out and let me know what you think.

**Comment by SamSchott** [comment]
This has been released in v0.3.2 now. But it needs to be configured through the command line.

**Comment by rctneil** [comment]
@samschott I've just added a second DB account using the command line.  I wish to look at the preferences of this second account using the GUI but when I try it asks me to run `pip3 install maestral[gui]`.

When I do that I get `zsh: no matches found: maestral[gui]`

Any ideas?

**Comment by techman83** [comment]
Wrap it in qoutes `"maestral[GUI]"`, zsh is funny about square brackets.

**Comment by samschott** [comment]
@rctneil, indeed square brackets have a special meaning in `zsh` so you'll need to wrap the expression in quotes.

That being said, if you have installed the macOS app bundle, you should not be seeing this prompt since you already have the GUI installed. This is a bug in the current release, due to some missing metadata in the app bundle. To work around it, you can launch a GUI with the new config as follows:
```console
$ /Applications/Maestral.app/Contents/MacOS/Maestral -c CONFIG_NAME
```

If you do install the Python package with `pip3 install "maestral[gui]"`, you'll have both the Python package and the app bundle installed side by side. This might be a bit confusing but won't be a problem either.

**Comment by samschott** [comment]
Those warning is absolutely fine and don't affect functionality. To answer your questions:

> Once this works, will both accounts have their own Maesral app icon in the menu bar?

Yes, every account will have its separate GUI, including menu bar icon. I have never gotten around to writing a single user interface that can handle multiple accounts.

> If I open the Maestral app from my Applications folder, which will open?

It will open the account which you linked first, under the default config name "maestral".

Note that the "Start on login" option in the preference pane works independently for each configuration. If you check that option for each account, the next time you log in you will have two instances of Maestral running, one for each account.

If you don't like cluttering your menu bar like this, you can also start the sync-daemon only with the CLI option:
```console
$ maestral autostart -Y -c CONFIG_NAME
```
You will still receive desktop notifications for any changes and can always attach a GUI to the running daemon with
```console
$ maestral gui -c CONFIG_NAME
```
once this works again.

**Comment by rctneil** [comment]
@samschott Thanks for the answers.   In regards to the error. When that appears, the terminal is stuck. I need to Ctrl + C to get it to exit.  Also, no GUI window appears.

Sorry for not explaining fully.

**Comment by samschott** [comment]
> the terminal is stuck. I need to Ctrl + C to get it to exit.

The terminal will remain "stuck" until you quit the new Maestral instance again. If you don't want it to block, you can append the character `&` to the command. This will sent the program to the background.

> Also, no GUI window appears.

Are you sure? There should be a second menu bar icon popping up. On the newest MacBooks, it appears that this can sometimes be hidden by the notch.

**Comment by rctneil** [comment]
@samschott   Let me give it another test tomorrow when i'm back on that machine.

Will the multi account stuff get added to the GUI sometime? Just to make the whole process easier for the vast majority of users?

Really appreciate your quick replies!

**Comment by pryley** [comment]
@rctneil 

1. Open Terminal
2. Link a new Dropbox: `maestral gui -c personal`
3. Open the Maestral preferences and enable "Start Maestral on login"
4. Pause syncing and quit Maestral
5. Restart Terminal
6. `launchctl start com.samschott.maestral.personal.plist`

You can now quit Terminal and Maestral will continue to run.

**Comment by jgaryellison** [comment]
Several months ago I got two icons for multiple Maestral accounts, but it got messed up when I tried to update Maestral. I've tried many times uninstalling and reinstalling Maestral and following the five steps above, but I can only get one account to work at a time. It looks simple, but I cannot get it to work again.
