### ISSUE TITLE
Pip install fails, need pip3. 

### ISSUE THREAD

**Issue by jbrepogmailcom** [SamSchott/maestral-dropbox#29]
pi@raspiserver4:~ $ pip install --upgrade maestral
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting maestral
  Could not find a version that satisfies the requirement maestral (from versions: )
No matching distribution found for maestral

**Comment by jbrepogmailcom** [comment]
worked with pip3. Maybe instructions need to be updated?

**Comment by SamSchott** [comment]
The system requirements clearly state that Maestral requires Python 3.6 or higher. Whether "pip" invokes the Python 2 or 3 version depends on your environment, if you have symlinked "pip" to pip2 or pip3, etc.

Maybe it is indeed better to explicitly point to pip3. I had thought that the Python requirement was clear form the readme.

**Comment by jbrepogmailcom** [comment]
Python3 requirement is after installation instructions. So everyone who is horny for installation starts to read README from beginning and learns he should run pip.

**Comment by logix2** [comment]
On some Linux distributions (e.g. Arch), pip uses Python3, while on others you need to use pip3 for Python3, that's why it's recommended to use ``python3 -m pip install``

**Comment by SamSchott** [comment]
Alright, I updated the installer instructions in 5a8945b95fb629f83d9e56095f577f4a458de117.
