### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by jbrepogmailcom** [SamSchott/maestral-dropbox#30]
After the installation:

...
Installing collected packages: pathtools, PyYAML, argh, watchdog, dropbox, u-msgpack-python, maestral
Successfully installed PyYAML-5.1.1 argh-0.26.2 dropbox-9.4.0 _maestral_-0.2.3 pathtools-0.1.2 u-msgpack-python-2.5.1 watchdog-0.9.0
**pi@raspiserver4:~ $ _meastral_
-bash: _meastral_: command not found**

Instructions are not clear if the app name is meastral or maestral...

**Comment by SamSchott** [comment]
Well, thats embarrassing. It should very much be "Maestral".

**Comment by jbrepogmailcom** [comment]
Please correct the installation instructions, thank you

**Comment by SamSchott** [comment]
Done in cdd47443093e859293f6cd82f26ab52e448c6413.
