### ISSUE TITLE
Doesn't find configuration if run under systemd

### ISSUE THREAD

**Issue by peterhoeg** [SamSchott/maestral-dropbox#34]
Installing from github (I'm packing it for NixOS), I am able to launch both the cli and gui applications and sync succesfully without any problems.

However, if I try running ```maestral sync``` from a systemd user service, it keeps prompting to go through the authorization process, so I am guessing that due to the different environment exposed to the systemd service, it is not able to find its configuration:
```
Aug 07 12:50:11 mildred maestral[435329]: Warning: PyQt5 is required to run the Maestral GUI. Run `pip install pyqt5` to install it.
Aug 07 12:50:11 mildred maestral[435329]: 1. Go to: https://www.dropbox.com/oauth2/authorize?response_type=code&client_id=oht3qeriq0h97xc
Aug 07 12:50:11 mildred maestral[435329]: 2. Click "Allow" (you might have to log in first).
Aug 07 12:50:11 mildred maestral[435329]: 3. Copy the authorization code.
Aug 07 12:50:11 mildred maestral[435329]: Enter the authorization code here:
Aug 07 12:50:11 mildred maestral[435329]: Aborted!
```

I am setting both HOME, DROPBOX_API_KEY and DROPBOX_API_SECRET in the systemd environment.

```ini
[Unit]
Description=Maestral - a Dropbox clone

[Service]
Environment="HOME=%h"
Environment="LOCALE_ARCHIVE=/nix/store/aqyxqxbxv1pcc52j71ba6jlzdyhgy5d3-glibc-locales-2.27/lib/locale/locale-archive"
Environment="PATH=/nix/store/k8lhqzpaaymshchz8ky3z4653h4kln9d-coreutils-8.31/bin:/nix/store/gjh3a8hqic3bqc2xzj8g2qxwz81wfjxx-findutils-4.6.0/bin:/nix/store/agcay3wmf74qinwshnjqy73w8rxf82hs-gnugrep-3.3/bin:/nix/store/vnyd3wh5i5kj66n9c5b8shzxjjrw22cn-gnused-4.7/bin:/nix/store/md7jdq475ij8cpifxb5rrh7y51qrfypq-systemd-242/bin:/nix/store/k8lhqzpaaymshchz8ky3z4653h4kln9d-coreutils-8.31/sbin:/nix/store/gjh3a8hqic3bqc2xzj8g2qxwz81wfjxx-findutils-4.6.0/sbin:/nix/store/agcay3wmf74qinwshnjqy73w8rxf82hs-gnugrep-3.3/sbin:/nix/store/vnyd3wh5i5kj66n9c5b8shzxjjrw22cn-gnused-4.7/sbin:/nix/store/md7jdq475ij8cpifxb5rrh7y51qrfypq-systemd-242/sbin"
Environment="QML2_IMPORT_PATH=/nix/store/qa3faa7dy41wxd1y2ldmg5fzc3pdwb10-qtbase-5.12.0-bin/lib/qt-5.12/qml"
Environment="QT_PLUGIN_PATH=/nix/store/qa3faa7dy41wxd1y2ldmg5fzc3pdwb10-qtbase-5.12.0-bin/lib/qt-5.12/plugins"
Environment="TZDIR=/nix/store/fsfddn3jj009rgy80fdv50lq13sp1p73-tzdata-2019a/share/zoneinfo"
EnvironmentFile=%t/keys/maestral
ExecStart=/nix/store/cmd69mskpzvp3adbgkhpl49bci65lrkb-maestral-0.2.4/bin/maestral sync
Nice=10
Restart=on-failure
```

**Comment by SamSchott** [comment]
There might be two reasons for this:

1) Maestral cannot find the config file and therefore does not load the Account ID. It will first try to find the home directory via `os.path.expanduser('~')`. If the return value is not a directory, it will query the environment variables 'HOME', 'USERPROFILE' and 'TMP' (in that order) and read or create a config file there. If none of this works, Maestral will raise an error.

2) Maestral does find the config files but cannot access your system keyring to retrieve the auth key. Maestral should then crash with an informative error message, so this is unlikely. But the `keyring` package might fall back to an alternative storage location if it cannot access the preferred keyring. This selection process is documented [here](https://pypi.org/project/keyring/#configure-your-keyring-lib) and you can find more information on accessing the keyring in headless systems [here](https://pypi.org/project/keyring/#using-keyring-on-headless-linux-systems).

I have added debug statements to print the used keyring location, as well as the home folder / config file directory and switched the logging level to debug. Could you check what the output is?

If this is indeed a keyring issue, I can fore Maestral to always stick to the keyring which was used during linking.

**Comment by peterhoeg** [comment]
> If the return value is not a directory, it will query the environment variables 'HOME', 'USERPROFILE' and 'TMP' (in that order) and read or create a config file there.

I actually had a quick look at the code before reporting this which is why I tried specifically setting ```HOME``` in the systemd unit.

> but cannot access your system keyring to retrieve the auth key.

I think this is it. The problem with the headless option is that it still requires user interaction (to type in the unlock password) which simply isn't doable if maestral is run by systemd as stdin/stdout is handled by systemd. 

About from master:
```
Aug 07 20:48:12 dolores maestral[101181]: Using config directory: /home/peter/.config/maestral
Aug 07 20:48:12 dolores maestral[101181]: Warning: PyQt5 is required to run the Maestral GUI. Run `pip install pyqt5` to install it.
Aug 07 20:48:12 dolores maestral[101181]: 2019-08-07 20:48:12 maestral.oauth DEBUG: Using keyring: keyrings.alt.file.PlaintextKeyring (priority: 0.5)
Aug 07 20:48:12 dolores maestral[101181]: 1. Go to: https://www.dropbox.com/oauth2/authorize?response_type=code&client_id=oht3qeriq0h97xc
Aug 07 20:48:12 dolores maestral[101181]: 2. Click "Allow" (you might have to log in first).
Aug 07 20:48:12 dolores maestral[101181]: 3. Copy the authorization code.
Aug 07 20:48:12 dolores maestral[101181]: Enter the authorization code here:
Aug 07 20:48:12 dolores maestral[101181]: Aborted!
```

**Comment by SamSchott** [comment]
From the logs, it looks like the keyring package is falling back to plain text storage of the auth token. This is horribly insecure, unless your user files are encrypted. Your easiest option would be to complete the authentication process with this plain text backend (for instance, after manually starting a headless session). It will then be saved for future launches with systemd.

Depending on the default keyring that you use, there are ways to unlock it for a headless sessions. Maestral installs the `keyring.alt` package, which also provides direct access to the Gnome Keyring without needing a D-Bus session. Your can start the `gnome-keyring-daemon` without needing a display manager: [https://wiki.archlinux.org/index.php/GNOME/Keyring](https://wiki.archlinux.org/index.php/GNOME/Keyring). But this will be more involved.

**Comment by peterhoeg** [comment]
Running this under KDE on NixOS where the python keyring module didn't bring in ```dbus-python``` so there was no way for it to communicate with kwallet.

After I fixed that, things have now started working properly and the password is stored in kwallet.

Ref: https://github.com/NixOS/nixpkgs/pull/68478
