### ISSUE TITLE
Feature Request - write config to $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by peterhoeg** [SamSchott/maestral-dropbox#35]
On linux, it's generally frowned upon to write directly to a directory under $HOME. Instead write the config to $XDG_CONFIG_HOME which defaults to $HOME/.config.

The directory should also change accordingly, so that:

```$HOME/.maestral``` becomes ```$XDG_CONFIG_HOME/maestral```

**Comment by peterhoeg** [comment]
The logs should then go into $XDG_DATA_HOME/maestral as well.

**Comment by SamSchott** [comment]
Agreed. I will change that in the next release.

**Comment by SamSchott** [comment]
Fixed in ccc398c76b4d8ef57f650577ea01f24ea231c806. Config files are now saved in either '$XDG_DATA_HOME/maestral' on Linux or '~/Application Support/maestral' on macOS. On initial run, the old config files are migrated to the new location.

I would not want people to frown upon this project...

**Comment by peterhoeg** [comment]
Damn, you're a *machine*! Nicely done. :+1:

**Comment by SamSchott** [comment]
Yeah, I was planning to do this for a while. I just never got to it.

**Comment by peterhoeg** [comment]
> Config files are now saved in either '$XDG_DATA_HOME/maestral' on Linux

Just to clarify - according to the code and observed behaviour, you are using ```$XDG_CONFIG_HOME/maestal``` on linux.

**Comment by SamSchott** [comment]
Yeah, I just correct that.

Also, log files are for the time being still stored in the same directory as the config files. I will change that in a future commit, my priority was not to clutter the home directory for now.

**Comment by SamSchott** [comment]
Moved logs to '$XDG_CACHE_HOME/maestral' on Linux and '~/Library/Logs/maestral' on macOS in 7ce1e57d33f5ad499f3bc41deeb7b5c6c1fd3f0c.
