### ISSUE TITLE
Feature Request - support for software watchdog

### ISSUE THREAD

**Issue by peterhoeg** [SamSchott/maestral-dropbox#55]
When running under systemd, if you continue sending ```READY=1``` at an interval, systemd can enable watchdog mode, where it will automatically restart the service in case the heartbeat doesn't come.

The standard is to send it at an interval of ```$WATCHDOG_USEC / 2```. The variable is set by systemd.

**Comment by SamSchott** [comment]
Shouldn't it be `WATCHDOG=1` instead of `READY=1`?

**Comment by peterhoeg** [comment]
Imagine a brainfart emoji here.... Yes, indeed, thanks! I'll do up a PR with the systemd configuration by the way. Now, when installing via pip, it isn't going to make a difference, but for distribution provided packages, it would work.

**Comment by SamSchott** [comment]
done in v0.4.1
