### ISSUE TITLE
Document configuration sections & keys

### ISSUE THREAD

**Issue by jakajancar** [SamSchott/maestral-dropbox#61]
It would be helpful if the configuration options were documented. E.g., I don't understand the difference between `main.path` and `main.default_dir_name`.

Also, seems like some of it isn't even configuration, but just stored state?

**Comment by SamSchott** [comment]
A documentation of config options has been added to the [Wiki](https://github.com/SamSchott/maestral-dropbox/wiki/Config-File) and state info is now stored separately from v0.6.2.
