### ISSUE TITLE
[BUG] Application version 0.4.2 will not launch in Catalina

### ISSUE THREAD

**Issue by rjroch** [SamSchott/maestral-dropbox#64]
**Describe the bug**
Unable to launch the unzipped Maestral.app.

**To Reproduce**
Unzip [https://github.com/SamSchott/maestral-dropbox/releases/download/v0.4.2/Maestral.app.zip](url) and attempt to launch it.

**Expected behaviour**
The application would launch.

**System (please complete the following information):**
 - Maestral version: 0.4.2
 - OS: MacOS Catalina 10.15

**Additional context**
MacOS Console app displays the following messages:
Finder - LAUNCHING:0x0-0x4f04f Maestral foreground=0 bringForward=0 seed=114 userActivityCount=0
LoginWindow - -[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Maestral
kernel - Library Validation failed: Rejecting '/Applications/Maestral.app/Contents/MacOS/Python' (Team ID: none, platform: no) for process 'main(854)' (Team ID: none, platform: no), reason: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
LoginWindow - -[PersistentAppsSupport applicationQuit:] | for app:Maestral, _appTrackingState = 2

**Comment by SamSchott** [comment]
Ah, damn. This is because it is signed with a test certificate. The main audience really are Linux users, so I have not bothered to enrol in the Apple Developer Program.

The reason why the app is signed at all: it appears that one can only send Notification Center messages from signed apps.

**Comment by SamSchott** [comment]
Could you try the attached build? It should run successfully with "right-click -> Open" but user notifications will not work.

[Maestral.app.zip](https://github.com/SamSchott/maestral-dropbox/files/3785687/Maestral.app.zip)

**Comment by rjroch** [comment]
I did also try installing with python3/pip, and was able to complete
initial configuration, but afterward the app immediately crashed. The build
you've attached picked up right where the pip install left off, and is now
syncing away. I must say, I love the lighter footprint. The official
Dropbox client is so incredibly bloated these days.

**Comment by SamSchott** [comment]
I'm glad that you like the program! For now, I have pulled the signed version from the releases page and may replace it with an unsigned build later.

What exactly went wrong when running it from Python? Do you have a crash log?

**Comment by rjroch** [comment]
Sam,

Turns out it was just not having my user's ~/Library/Python/3.7/bin in my
path. I didn't expect that to be an issue since Maestral's GUI ran through
initial Dropbox linking and other configuration just fine.

I just reinstalled Maestral and pyqt5 via:
python3 -m pip install --user --upgrade pyqt5
python3 -m pip install --user --upgrade maestral

--user installs in MacOS go to ~/Library/Python/PythonVersion so to run
Maestral I ran:
~/Library/Python/3.7/bin/maestral gui

The traceback I get is as follows:
Traceback (most recent call last):
  File "/Users/Randy/Library/Python/3.7/bin/maestral", line 10, in <module>
    sys.exit(main())
  File
"/Users/Randy/Library/Python/3.7/lib/python/site-packages/click/core.py",
line 764, in __call__
    return self.main(*args, **kwargs)
  File
"/Users/Randy/Library/Python/3.7/lib/python/site-packages/click/core.py",
line 717, in main
    rv = self.invoke(ctx)
  File
"/Users/Randy/Library/Python/3.7/lib/python/site-packages/click/core.py",
line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File
"/Users/Randy/Library/Python/3.7/lib/python/site-packages/click/core.py",
line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File
"/Users/Randy/Library/Python/3.7/lib/python/site-packages/click/core.py",
line 555, in invoke
    return callback(*args, **kwargs)
  File
"/Users/Randy/Library/Python/3.7/lib/python/site-packages/maestral/cli.py",
line 188, in gui
    run()
  File
"/Users/Randy/Library/Python/3.7/lib/python/site-packages/maestral/gui/main.py",
line 517, in run
    maestral_gui.load_maestral()
  File
"/Users/Randy/Library/Python/3.7/lib/python/site-packages/maestral/gui/main.py",
line 142, in load_maestral
    self.mdbx = self._get_or_start_maestral_daemon()
  File
"/Users/Randy/Library/Python/3.7/lib/python/site-packages/maestral/gui/main.py",
line 152, in _get_or_start_maestral_daemon
    start_maestral_daemon_process(CONFIG_NAME)
  File
"/Users/Randy/Library/Python/3.7/lib/python/site-packages/maestral/sync/daemon.py",
line 181, in start_maestral_daemon_process
    stdin=STD_IN_OUT, stdout=STD_IN_OUT, stderr=STD_IN_OUT,
  File
"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py",
line 775, in __init__
    restore_signals, start_new_session)
  File
"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/subprocess.py",
line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'maestral':
'maestral'

So I added ~/Library/Python/3.7/bin to my path and now both GUI and CLI
work just fine. Please let me know if you need anything else!
Randy

**Comment by SamSchott** [comment]
Perfect, good to know!

Yes, Maestral runs the gui and the sync daemon in separate processes. If the `maestral` command cannot be found in your PATH, starting the sync daemon will fail.

This has the advantage that you can run the daemon without a gui through `maestral start` (which typically halves memory and CPU usage) and run the gui only when needed. But it clearly also has disadvantages...
