### ISSUE TITLE
[BUG] maestral 0.5.0 crashes after mouse-over on LinuxMint 19.2

### ISSUE THREAD

**Issue by rscircus** [SamSchott/maestral-dropbox#77]
**Describe the bug**
maestral 0.5.0 crashes after mouse-over on LinuxMint 19.2 with the following message:

```
python3: ../src/mesa/drivers/dri/i965/brw_disk_cache.c:405: brw_disk_cache_init: Assertion `note && build_id_length(note) == 20' failed.
```

**To Reproduce**
Start maestral in the console

```
maestral gui
```

wait until the icon appears in the panel and move your mouse cursor over it.

**Expected behaviour**
Expected to right click it and see the menu which is already known

**System (please complete the following information):**
 - Maestral version: 0.5.0
 - OS: Linux Mint 19.2
 - Desktop environment: Cinnamon 4.2.4+tina
 - Qt version: 5.14.0

**Comment by SamSchott** [comment]
This looks like an issue with Qt / PyQt and the intel graphics driver. I can't reproduce this on a virtual machine running a similar configuration of Linux Mint so its very hard to debug.

Did you install PyQt5 from the system repo or from PyPI? And did you update anything else besides Maestral at the same time?

**Comment by SamSchott** [comment]
Any updates on this?

**Comment by rscircus** [comment]
Hi @SamSchott - thanks for coming back to this. Meanwhile I actually switched to https://syncthing.net/ which works very nicely on all my platforms for me and is also way more trustworthy in times of privacy awareness and such...

**Comment by SamSchott** [comment]
No worries, syncthing is a good alternative. Especially if you don't want your files on some else's server.
