### ISSUE TITLE
[BUG] Exclude folder fails with AttributeError

### ISSUE THREAD

**Issue by ashb** [SamSchott/maestral-dropbox#79]
**Describe the bug**
Trying to exclude a top-level folder in my drop box fails with this error

**To Reproduce**

```
$ maestral excluded add  Ash\'s\ PSF2011\ Videos
Excluded directory '/Ash's PSF2011 Videos'.
Exception ignored in: <function Proxy.__del__ at 0x7f00d38f85e0>
Traceback (most recent call last):
  File "/home/ash/.virtualenvs/maestral/lib/python3.8/site-packages/Pyro5/client.py", line 80, in __del__
AttributeError: 'NoneType' object has no attribute 'suppress'
```

**System (please complete the following information):**
 - Maestral version:
 - OS: ArchLinux
 - Desktop environment: KDE
 - Qt version: (QT5, but not using GUI, and PyQt5 not installed)

**Additional context**

Fresh install in virtual env just now

<details>

<summary>Packages installed</summary>
```
argh==0.26.2
blinker==1.4
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
Click==7.0
cryptography==2.8
dropbox==9.4.0
idna==2.8
jeepney==0.4.2
keyring==21.1.0
keyrings.alt==3.4.0
maestral==0.5.0
pathtools==0.1.2
pycparser==2.19
Pyro5==5.6
PyYAML==5.3
requests==2.22.0
SecretStorage==3.1.2
serpent==1.28
six==1.13.0
u-msgpack-python==2.5.2
urllib3==1.25.7
watchdog==0.9.0
```

</details>

**Comment by ashb** [comment]
Oh though I just noticed that it did actually update the exclusion list.

**Comment by SamSchott** [comment]
Yeah, that as [known issue](https://github.com/irmen/Pyro5/issues/17) with the upstream library `Pyro5` v5.6 which I noticed too late to adjust the dependencies. It has already been fixed but the new version has not been released yet.

For now, you can either downgrade to Pyro5 v5.5.1 or live with a few ugly but harmless Python exceptions when a CLI command completes.

**Comment by SamSchott** [comment]
Minimum requirements have now been bumped to Pyro5 5.7.
