### ISSUE TITLE
No tray bar icon in Fedora

### ISSUE THREAD

**Issue by idnovic** [SamSchott/maestral-dropbox#8]
I have no traybar icon in linux after I started maestral-gui

fedora 30
gnome wayland

**Comment by SamSchott** [comment]
@idnovic, can you give some details? Which linux distribution are you using? Do you see any error messages? Does it sync successfully?

I have only tested Maestral on macOS 10.14 and CentOS 6 so far.

**Comment by idnovic** [comment]
I am using fedora 30 on gnome wayland. Yes it does sync successfully. But no tray icon. I do not get any log indicating an problem. I played a bit and found out that Maestral was not able to sync the original dropbox folder so I deleted the content and resynced. Works good and uses half the resources of the original dropbox client. I created a backup just to be sure.

I can see the original dropbox icon when I am using it. Currently deactivated for maestral.

**Comment by SamSchott** [comment]
I'm glad that its working well for you, apart from the missing system tray icon. In my experience, Maestral is very robust, I have only encountered occasional falsely detected sync conflicts but this should already be resolved. 

Regarding the missing icon, I have looked into it and there seems to be no easy way to fix the issue. Maestral uses Qt / PyQt for its user interface which cannot show a tray icon in the absence of a system tray in Gnome. One should ideally write a native GTK user interface to support this.

In the meantime, you can access most settings through the command line. Just type `maestral --help` to get all options. If you install the latest version, the will also be a command to automatically start Maestral on login.

**Comment by idnovic** [comment]
I am using this extension to be able to use tray icons
https://github.com/zhangkaizhao/gnome-shell-extension-tray-icons

Can you refer me an other app that uses the same technical function for the tray icon? I would make sure the other can display the tray icon.

I also used to use https://github.com/ubuntu/gnome-shell-extension-appindicator
but I am not currently. I did try it but it did not add the maestral tray icon.

What tray icon method is maestral using? Can you point me the the source code responsible?

**Comment by idnovic** [comment]
these are the errors I get in the terminal:

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread

```

You can ignore the wayland part. Is the QSocketNotifier important?

**Comment by idnovic** [comment]
I can add that the notification after I added a file on my iPhone to dropbox does display on my laptop with linux. So notification seems to works as well for new files and deleted files.

**Comment by SamSchott** [comment]
The system tray icon is created using `QSystemTrayIcon` ([https://doc.qt.io/Qt-5/qsystemtrayicon.html](https://doc.qt.io/Qt-5/qsystemtrayicon.html)). Another app uses the same approach is [Telegram](https://github.com/telegramdesktop/tdesktop), but I don't know if they have the same issue on Gnome.

Notifications are currently handled by `notify-send` and not the system tray, this is why they still work.

**Comment by idnovic** [comment]
okay I got the tray icon to work with this extension
https://github.com/ubuntu/gnome-shell-extension-appindicator

Just the icon is missing. It seems not to be an error of maestral.
The tray works even though without icon it is hit and miss to find it.
Settings menu does work too.

Still gnome is officially removing tray support. To be able to open the settings gui directly could be useful.

Thank you.

**Comment by SamSchott** [comment]
Glad it worked, more or less. Yes, its an issue with Gnome no longer liking tray icons. The official Dropbox client ran into exactly the same problem, documented [here](https://www.dropboxforum.com/t5/Desktop-client-builds/Beta-Build-64-3-120/td-p/317407), and decided to use a GTK native app indicator for certain Gnome desktops instead. This is ultimately the best approach, but will take some time to implement.

**Comment by idnovic** [comment]
What about the following in the meantime:

open maestral-gui to just open the hidden application with tray indicator.
open maestral-gui again to open the settings window directly while maestral is running.

So I was thinking if maestral-gui does not lock the settings file then a startup check for a running maestral-gui process could be useful. If maestral-gui is already running just open the settings ui without initializing any sync stuff. After the user closed the settings ui the background process of maestral-gui is notified of the settings file change and adjusts to the new settings. File polling of the settings file could work but I think a simple hack would be for the foreground settings ui to create a .settings file inside the dropbox folder. The background maestral-gui process would see this file, delete it and reimport the settings. The .settings file is empty and is just indicating a settings change.

**Comment by SamSchott** [comment]
@idnovic, I just tested this myself on Fedora 29. The icon show up just fine with the appindicator extension installed. The problem is that it is black, and unlike macOS, Gnome does not automatically adapt the icon color to its system tray color. I have included a manual detection of the system tray color now and added resources for white icons. This should fix your remaining problems.

**Comment by idnovic** [comment]
yes it s fixed for me. The other tweaks about the layout look nice too :)

**Comment by SamSchott** [comment]
Great :)
