### ISSUE TITLE
[Feature Request] Include optional systemd unit and xdg autostart files.

### ISSUE THREAD

**Issue by bbaserdem** [SamSchott/maestral-dropbox#83]
I have been packaging maestral for Arch Linux distribution. A suggestion was sent to me about including systemd unit files to run maestral as a daemon. Currently, I ship my own unit files along with the package.

I do not know much about python packaging; but maybe the package can supply systemd unit files for system level installations? Currently I have [this](https://aur.archlinux.org/cgit/aur.git/tree/maestral-config@.service?h=maestral-git) and [this](https://aur.archlinux.org/cgit/aur.git/tree/maestral.service?h=maestral-git), which I can confirm that works well; and covers both the case where there is a single user instance and multiple user instances. (These files would be put in `/usr/lib/systemd/user`)

If such files can be provided with a package, for launching the GUI on desktop login in linux; there is the XDG standart which all popular display environments in linux adhere to. I can also supply [my own autostart file](https://github.com/bbaserdem/dotfiles/blob/master/autostart/maestral.desktop), which would go in `/etc/xdg/autostart`.

**Comment by SamSchott** [comment]
Good to see that Maestral is being packaged for Arch Linux!

I have considered bundling systemd unit files but have not (yet) done so for a few reasons: 

* Not all platforms which Maestral supports are using systemd. Exceptions include macOS and older Linux distributions. Maestral started as a way to keep using Dropbox on CentOS 6.

* There does not seem to be a good way to install system files in a platform-independant way when using Python packages. For instance, on macOS, one should ship launchd files instead.

* People prefer different setups for systemd and I do not want to enforce a default which gets overwritten with every update.

There are however instructions on the [Wiki](https://github.com/SamSchott/maestral-dropbox/wiki/Systemd-Integration) on setting up systemd and launchd. Your files are almost exactly the same.

The only issue with your template may be with the ExecReload command: `maestral restart` terminates the current daemon and spawns a new daemon process. But systemd will expect it to start the process in its current process, as far as I understand. Also, there is a small typo: `restarat ` -> `restart`.

Regarding XDG desktop entries, this is supported when checking the 'Start on login' box in the settings GUI. This creates the appropriate entry at "$XDG_CONFIG_HOME/autostart/" on Linux and "~/Library/LaunchAgents/" on macOS.

**Comment by SamSchott** [comment]
Small addendum: In the next release, it will be possible to restart maestral into the current process instead of spawning a new process with `maestral restart --foreground`.

**Comment by bbaserdem** [comment]
Thank you. Did not notice the typo and will fix it, thank you.

So from what I understand, maestral, on restart, currently forks and quits. That could be handled within systemd with a unit type of forking and a pid file for systemd to keep track of; but if this behavior will change in the next release, then I see no point in trying to accommodate now.

I missed the autostart feature; thank you for pointing it out to me.

I'll close the issue since all my questions have been answered.

**Comment by SamSchott** [comment]
Support for this has now been added in v0.6.2. This includes:

* Taking care to give the correct path to the maestral script, depending on the user's installation.
* Using systemd on Linux and launchd on macOS. Other init systems are currently not supported.
* Creating startup entries which do not conflict with the GUI's "Start on login" function. This is especially relevant on macOS, where the GUI also uses launchd, and may become relevant to Gnome when they have fully migrated to systemd.
