### ISSUE TITLE
Question regarding right update method

### ISSUE THREAD

**Issue by idnovic** [SamSchott/maestral-dropbox#9]
I updated from 200e47b to 7b12245 by using 
`pip3 install --user git+https://github.com/SamSchott/maestral` (wrong, right command below, this does not replace the installed files)

can you tell me where this file comes from? The file is from the older install. I moved the binary of maestral-gui from /bin to /.bin
but I can not find the following file in the newer version. Do I need to update it?

```
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'maestral==0.1.1','console_scripts','maestral'
__requires__ = 'maestral==0.1.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('maestral==0.1.1', 'console_scripts', 'maestral')()
    )
```

**Comment by idnovic** [comment]
I found out to upgrade you need to do:

`pip3 install --user git+https://github.com/SamSchott/maestral --upgrade`

**Comment by idnovic** [comment]
My question above still remains

**Comment by SamSchott** [comment]
This file should be automatically created at the right place when installing with pip. Maestral currently installs two entry points in '~/.local/bin' or '/bin:

1) 'maestral-gui': This is just a script which calls `maestral gui`. But it can be used to modify the user environment if needed, before starting Maestral. 

2) 'maestral': The actual python command line program. This file is created during the installation and should therefore not be missing.

Could you try to uninstall and reinstall Maestral? All your settings will be preserved.

**Comment by SamSchott** [comment]
> I found out to upgrade you need to do:
>
> pip3 install --user git+https://github.com/SamSchott/maestral --upgrade

Yes, I'll update the README accordingly.

**Comment by idnovic** [comment]
okay so i did uninstall and installed again. Problem is you pushed the new version in the meantime, at least I can tell you this new version does replace the files in /.bin too. I do not know whatever it worked in the older.

**Comment by SamSchott** [comment]
I did not change anything related to the installation apart form bumping the version number to v.0.1.2-dev0. pip sometimes does not upgrade a package if the version number has not changed, so this may have helped. But I could not reproduce the issue on my side, with either version.

**Comment by idnovic** [comment]
Okay thank you. I close this issue since it works now as expected and new users should know how to upgrade.
