### ISSUE TITLE
Need help installing latest maestral version please

### ISSUE THREAD

**Issue by someone1233** [SamSchott/maestral-dropbox#91]
Hi,

I installed maestral v.0.5.2 for the first time on Linux Mint 19.1 Cinnamon a few weeks ago by following this guide exactly: https://www.linuxuprising.com/2019/07/maestral-is-new-open-source-dropbox.html & it's been working perfectly since then & I love it. (note: have since upgraded to Mint 19.3)

yesterday there was a notification about updating to the latest version so I tried to do it but am having problems, currently new maestral won't install right & I don't know enough about linux to roll back to the previous version if that is possible, so I am now maestralless :< if it is possible to get some help installing the latest version or going back to the old one I would really appreciate it.

I ran `python3 -m pip install --upgrade --user maestral` to do the update (and also added `--no-cache-dir` because there were errors about building wheels the first time) and `pip3 list` now shows the version as maestral (0.6.1.post1). typing `maestral gui` tells me to run the command to install the gui, but when I do that it fails with this error:

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-egbit_kw/PyQt5/`

in addition to that most of the maestral CLI commands (e.g. `maestral start`) give this error:

```
2020-02-29 21:13:55,919 - [bugsnag] WARNING - No API key configured, couldn't notify
Traceback (most recent call last):
  File "/home/user/.local/bin/maestral", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/maestral/cli.py", line 133, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/maestral/cli.py", line 305, in start
    from maestral.main import Maestral
  File "/home/user/.local/lib/python3.6/site-packages/maestral/main.py", line 37, in <module>
    from maestral.sync import MaestralMonitor
ImportError: cannot import name 'MaestralMonitor'
```

I'm very new to linux so have no idea at all how to proceed. I appreciate very much any help, thank you.

**Comment by SamSchott** [comment]
I'm sorry about the update experience - this update is a bit more intricate than previous ones because it splits off the gui and rearranges the config files. It wont be possible to downgrade easily without a full re-sync.

However, the issues in your case don't seem directly related to the above migrations but rather seem to be related to the install process itself. Since you were running the GUI before, I am surprised that pip attempts to install PyQt5. It should have already been installed. Does it show up in `pip3 list`? And if yes, which version? Or did you installed through the distribution's package manager?

Could you try the following?

1. Uninstall both `maestral` and `maestral-qt` (your configs will remain).
2. Update pip itself with `pip3 -U pip`. You should end up with version 20.0.2.
3. Reinstall maestral + gui with `pip3 -U --user maestral[gui]`.

**Comment by someone1233** [comment]
thank you very much!! maestral is back! :D 

PyQt5 was not shown with `pip3 list` but I checked in Software Manager & do see it in there as "Python-pyqt5". I think it was installed originally with this command `sudo apt install python3-pip python3-setuptools python3-pyqt5` from the guide I followed. 

here are the steps i did (Mint 19.3):

1. `sudo -H pip3 install --upgrade pip` to update pip to 20.0.2, 
2. then `python3 -m pip install --user maestral` which installed maestral v0.5.2, 
3. then `python3 -m pip install --upgrade --user maestral` which updated maestral to v0.6.1.post1 
4. and finally `python3 -m pip install --user maestral[gui]` to install the gui. 

Now maestral, maestral-qt, PyQt5, & and PyQt5-sip all show with `pip3 list` & maestral is working great again! i guess the maestral installation commands can probably be combined, but at least I got there :} thank you again for your prompt & helpful guidance! (and of course for wonderful maestral itself) I'm so happy it's back.

![image](https://user-images.githubusercontent.com/32484427/75732808-8cdda180-5cc1-11ea-8ca4-2a1dc1e8a96f.png)

**Comment by SamSchott** [comment]
I'm glad it worked.

You are right, the installation should be simpler. Typically `python3 -m pip install --upgrade maestral[gui]` should install the latest versions of both the daemon and the GUI. Future updates will automatically detect if the GUI is installed and update it together with the daemon.

And good find about the name of the wind :) It is indeed named after the Croatian Maestral which, unlike the French namesake, is a light summer wind that blows in the afternoon when the coast becomes warmer than the sea.
