### ISSUE TITLE
CLI install broken?

### ISSUE THREAD

**Issue by mrand** [SamSchott/maestral-dropbox#93]
**Describe the bug**

First time trying to install and run maestral...

```

~$ maestral --help
Traceback (most recent call last):
  File "/home/house/.local/bin/maestral", line 7, in <module>
    from maestral.cli import main
  File "/home/house/.local/lib/python3.5/site-packages/maestral/cli.py", line 226
    ctx.fail(f'Configuration \'{value}\' does not exist. You can list\n'
                                                                       ^
SyntaxError: invalid syntax
```

**To Reproduce**

Just trying to install and use for the first time.
Had to upgrade pip since I'm running 16.04

```
~$ python3 -m pip install --upgrade maestral     (this failed)
~$ sudo apt-get install python3-pip
~$ python3 -m pip install --upgrade maestral

```
**Expected behaviour**
CLI working

**System (please complete the following information):**
 - Maestral version: latest
 - OS: Ubuntu 16.04
 - Desktop environment: CLI
 - Qt version:

Let me know if you need any additional information!

**Comment by SamSchott** [comment]
It looks like you are using Python 3.5. Unfortunately, Maestral requires Python 3.6 or higher and the line which raises the error does contain syntax which is invalid in Python 3.5 ("f-strings").

**Comment by SamSchott** [comment]
Closing because Python 3.5 will not be added. However, proper Python version checks have been added to the installer.
