### ISSUE TITLE
Show notification error upon failure to even start maestral

### ISSUE THREAD

**Issue by coxackie** [SamSchott/maestral-dropbox#94]
**Describe the bug**
When `maestral` fails to start, for example because of a missing dependency, there is no desktop notification for the error. When using only the daemon, there is no way to know that something went wrong, and one is left to thing that syncing is going on (especially since notifications of local changes of files do not show up.)

**To Reproduce**
Using `systemd` to start the daemon on user log-in. Somehow force `maestral` to fail to start (for example, in my case, I accidentally have removed the dependency `serpent`). The daemon fails to start, but there is no notification of failure.

**Expected behaviour**
Notify not only in cases of sync failures, but importantly when the program fails to start.

**System (please complete the following information):**
 - Maestral version: 0.6.1
 - OS: Arch Linux
 - Desktop environment: 3.36
 - Qt version: NA

**Comment by SamSchott** [comment]
That is good point but not straight forward to implement.

Import errors are particularly difficult to handle because Maestral may use external dependencies for desktop notifications. This is the case for macOS and may become the case for Linux.

I am inclined to handle this with systemd itself: have a shell script which sends a notification if the daemon stopped with an error. For example, one could add a line to the systemd unit file:

```ini
ExecStopPost=/usr/bin/env bash -c "if [ $SERVICE_RESULT!=success ]; then notify-send Maestral 'Daemon failed'; fi"
```

This will work irrespective of any dependencies and will not send unneeded notifications when manually starting the service.

I am not sure if there is an equivalent hook for launchd.

**Comment by coxackie** [comment]
Sounds promising for Linux, at least for the time being. Maybe update the systemd service file in the wiki. I will test if it works ok.

**Comment by coxackie** [comment]
Seems to be working - one issue is that the notification is sent quite a number of times, as the service tries to restart upon failure. But this is a small price to pay for knowing that something went wrong...

**Comment by SamSchott** [comment]
Good that it works. I'll add it to the Wiki and maybe even to the service which is installed via `maestral autostart -Y`.

Well, the issue with multiple notifications would be there with any method. At least, this method is handles are all Python exceptions, even those before any notification code can be loaded.

**Comment by SamSchott** [comment]
I just tried the code snipped which I posted and its not quite right. The environment variable `SERVICE_RESULT` does not get passed to the script and it will therefore always send a failed notification when Maestral stops. The correct way of doing it:

```ini
ExecStopPost=/usr/bin/env bash -c "if [ ${SERVICE_RESULT}!='success' ];\
then notify-send Maestral 'Daemon failed'; fi"
```

**Comment by coxackie** [comment]
Hmmmm, I tried both the previous and the revised version, and I get the same: whenever I `systemctl --user restart maestral.service` I get a notification that the Daemon failed.

**Comment by SamSchott** [comment]
Stupid mistake, there should be spaces around the comparison operator:

```ini
ExecStopPost=/usr/bin/env bash -c "if [ ${SERVICE_RESULT} != 'success' ];\
then notify-send Maestral 'Daemon failed'; fi"
```

**Comment by SamSchott** [comment]
Closing since this has been added to the default service generated by `maestral autostart -Y`
