### ISSUE TITLE
How to autostart without Autostart?

### ISSUE THREAD

**Issue by D12EA177E12** [SamSchott/maestral-dropbox#98]
I am running maestral-dropbox on ArchLinux + i3 (without a desktop environment; hence lacks native Autostart support), but I'd like to autostart the maestral daemon without needing to enter my keyring password every time.  If I decide to use maestral-dropbox without a desktop environment (or alternatives like dapper, fbautostart, dex, ...), what would be a sensible way to autostart the maestral daemon?

 ̶T̶L̶D̶R̶;̶
̶I̶'̶v̶e̶ ̶l̶o̶o̶k̶e̶d̶ ̶a̶t̶ ̶y̶o̶u̶r̶ ̶c̶o̶d̶e̶ ̶t̶o̶ ̶u̶n̶d̶e̶r̶s̶t̶a̶n̶d̶ ̶h̶o̶w̶ ̶a̶u̶t̶h̶e̶n̶t̶i̶c̶a̶t̶i̶o̶n̶ ̶i̶s̶ ̶i̶m̶p̶l̶e̶m̶e̶n̶t̶e̶d̶ ̶a̶n̶d̶ ̶I̶ ̶b̶e̶l̶i̶e̶v̶e̶ ̶a̶ ̶q̶u̶i̶c̶k̶-̶a̶n̶d̶-̶d̶i̶r̶t̶y̶ ̶w̶a̶y̶ ̶w̶o̶u̶l̶d̶ ̶b̶e̶ ̶t̶o̶ ̶h̶a̶r̶d̶c̶o̶d̶e̶ ̶`̶a̶c̶c̶e̶s̶s̶_̶t̶o̶k̶e̶n̶`̶;̶ ̶ ̶b̶u̶t̶ ̶l̶e̶t̶'̶s̶ ̶f̶o̶r̶g̶e̶t̶ ̶t̶h̶i̶s̶ ̶i̶d̶e̶a̶ ̶f̶o̶r̶ ̶n̶o̶w̶.̶

**Comment by coxackie** [comment]
Maybe through a systemd service? Check the wiki entry: https://github.com/SamSchott/maestral-dropbox/wiki/Systemd-Integration

**Comment by SamSchott** [comment]
It depends a bit your setup. Are you using the Gnome keyring or KWallet as your default keyring? In either case, maestral needs a dbus-session to communicate with the keyring and the keyring to be unlocked inside the session. If none of those keyrings are installed, it will fall back to an encrypted file.

You can check which backend it is using by setting the log level to debug `maestral log level DEBUG` and checking in the logs. Alternatively, you can start the daemon in the foreground with `maestral start -f`. One of the first log outputs should be something like:

```
2020-03-20 14:03:10 maestral.oauth DEBUG: Using keyring: keyring.backends.SecretService.Keyring (priority: 5)
```

**Comment by D12EA177E12** [comment]
@coxackie I've followed the instructions at the wiki entry on Systemd-integration and it doesn't start the daemon automatically on login.

@SamSchott 
`[fkl@DigitalRealm ~]$ maestral start -f
Please enter password for encrypted keyring: 
2020-03-23 19:36:53 maestral.oauth DEBUG: Using keyring: keyrings.alt.file.EncryptedKeyring (priority: 0.6)`

Which keyring am I using?  Does the above output suggests that I am using an encrypted file as the keyring, and if so where might that file be located? What do I need to do in order to configure maestral to auto start on login?

**Comment by coxackie** [comment]
@D12EA177E12 it could be that the `systemd` service fails to start because of the keyring issue. Can you check and provide the output of `systemctl --user status maestral.service`?

**Comment by SamSchott** [comment]
> Does the above output suggests that I am using an encrypted file as the keyring, and if so where might that file be located?

Yes, it is falling back to an encrypted file. The file should be located at `~/.local/share/python_keyring/crypted_pass.cfg` and unfortunately there is no way to unlock it automatically on user login, unlike the keyrings provided by desktop environments.

The only way to autostart the daemon in this case would indeed require storing the Dropbox key in a plain text file. This is not too bad if your home directory is encrypted. But Maestral currently does not have an interface to choose how Dropbox credentials are stored, it simply chooses the most secure method it can find and sticks with that.

So for the time being, you will have to stick with entering the password manually. I also expect that the daemon may not start at all, since `maestral start` spawns a separate process which does not have access to the decrypted credentials anymore. So you may be stuck with `maestral start -f`.

I'll see if this can be improved, or if indeed a plain text file together with a warning message may be the better fallback option.

**Comment by SamSchott** [comment]
I've pushed a pre-release version to PyPI wich does exactly the above: It falls back to a plain text file if neither Gnome Keyring nor KWallet are available but issues a warning to the user. The encrypted file had several safety issues in the first place.

The dev release also allows selecting a (possibly custom) keyring backend in the config file. I've been using it for testing and the option may not end up in the final release.

You can try it out with:

```
pip3 install maestral==0.6.4.dev2
```

Pip will print a warning about `maestral-qt` (the GUI) requiring maestral v0.6.3 which you can safely ignore. Also, Maestral will prompt you to relink your Dropbox and select a Dropbox folder location. If you select the old location and `merge`, it will simply reindex the existing folder without downloading any files.

**Comment by D12EA177E12** [comment]
> @D12EA177E12 it could be that the `systemd` service fails to start because of the keyring issue. Can you check and provide the output of `systemctl --user status maestral.service`?
```
[fkl@DigitalRealm ~]$ sudo systemctl --user status maestral.service
[sudo] password for fkl: 
Failed to connect to bus: No such file or directory
```

**Comment by coxackie** [comment]
ok, you clearly need to follow what @SamSchott suggests.

**Comment by D12EA177E12** [comment]
> I've pushed a pre-release version to PyPI wich does exactly the above: It falls back to **a plain text** file if neither Gnome Keyring nor KWallet are available

@SamSchott Thanks for making a pre-release version available on PyPI.  Before I give it a try I'd like to familiarize with the format of ``crypted_pass.cfg`` (assuming that's the "plain text file").

Under the ``[Maestral]`` section of the ``crypted_pass.cfg`` file I can find a key/value pair that looks like the following:
```dbid_<id_string> = <280-character-char-string>```

whereas the ```access_token``` retrieved via ``` keyring.get_password('Maestral', account_id)```
is a 64-character string.
Could you tell me why they are different?

**Comment by SamSchott** [comment]
The 280-character string is the encrypted token. The plain text token would be stored in a file `keyring_pass.cfg` at the same location.

**Comment by D12EA177E12** [comment]
I see.  Now, do I have to manually prepare ``keyring_pass.cfg`` myself or will it be taken care of by version 0.6.4.dev2 ?

**Comment by SamSchott** [comment]
Well, `keyring_pass.cfg` will be created by 0.6.4.dev2 but it will be empty. Maestral will prompt you to relink your account and trigger a reindexing. That may take some time, depending on the size of your Dropbox...

If you would like a seamless transition, you can copy the decrypted token over to `keyring_pass.cfg` before restarting Maestral. The following Python commands should do the job:

```Python
import keyrings.alt

ring_old = keyrings.alt.file.EncryptedKeyring()
ring_new = keyrings.alt.file.PlaintextKeyring()

creds = ring_old.get_credential('Maestral', 'dbid:1234')
ring_new.set_password('Maestral',  creds.username,  creds.password) 
```
`'dbid:1234'` should be replaced with your Dropbox ID as returned by `maestral account-info` and **not** the value listed in the `crypted_pass.cfg` file.

**Comment by D12EA177E12** [comment]
>  The following Python commands should do the job:
Yes indeed. Thanks for the support!
